[tools]
awscli = "latest"
python = "3.13"
task = "latest"
terraform = "latest"
uv = "latest"
tf-summarize = "latest"
tflint = "latest"
terraform-docs = "latest"
tfsec = "latest"
jq = "latest"
terrascan = "latest"